name: Sign
description: "Sign Release Files"
inputs:
  grs_username:
    description: "The garasign username"
  grs_password:
    description: "The garasign password"
  art_user:
    description: "The artifactory username"
  art_password:
    description: "The artifactory password"
  art_image:
    description: "The artifactory image"

runs:
  using: composite
  steps:
    - name: Create the envfile
      shell: bash
      run: |
        cat << EOF > envfile
        GRS_CONFIG_USER1_USERNAME=${{ inputs.grs_username }}
        GRS_CONFIG_USER1_PASSWORD=${{ inputs.grs_password }}
        EOF
    - name: Log in to artifactory
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ inputs.art_user}}
        password: ${{ inputs.art_password }}
        registry: artifactory.corp.mongodb.com
    - name: Generate the signature files in a container
      shell: bash
      run: |
        podman run \
          --env-file=envfile \
          --rm \
          -v $(pwd):$(pwd) \
          -w $(pwd) \
          ${{ inputs.art_image }} \
          /bin/bash -c "$(pwd)/scripts/generate-signatures.sh"
