
name: Publish
description: "Asset Publish Action"
inputs:
  version:
    description: "The published version"
    required: true
  garasign_username:
    description: "The garasign username"
    required: true
  garasign_password:
    description: "The garasign password"
    required: true
  artifactory_username:
    description: "The artifactory username"
    required: true
  artifactory_password:
    description: "The artifactory password"
    required: true
  aws_role_arn:
    description: "The aws role arn to assume"
    required: true
  aws_bucket_name:
    description: "The aws s3 bucket name"
    required: true
  aws_region:
    description: "The aws region for the s3 bucket"
    required: true
  token:
    description: "The GitHub access token"
    required: true
  dry_run:
    description: "Whether this is a dry run"
    required: true

runs:
  using: composite
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: all-dist-${{ github.run_id }}
        path: dist/
    - uses: mongodb-labs/drivers-github-tools/garasign/gpg-sign@main
      with:
        garasign_username: ${{ inputs.garasign_username }}
        garasign_password: ${{ inputs.garasign_password }}
        artifactory_username: ${{ inputs.artifactory_username }}
        artifactory_password: ${{ inputs.artifactory_password }}
        filenames: dist/*
    - name: Move the signature files to a separate directory
      shell: bash
      run: |
          set -eux
          mkdir signatures
          mv dist/*.sig signatures
    - uses: mongodb-labs/drivers-github-tools/papertrail@main
      with:
          product_name: winkerberos
          release_version: ${{ inputs.version }}
          filenames: dist/*
          token: ${{ inputs.token }}
    - name: Show files
      shell: bash
      run: |
        ls -ltr signatures/*
        cat papertrail.txt
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        role-session-name: s3uploadsession
        aws-region: ${{ inputs.aws_region }}
    - name: Upload signatures to s3
      shell: bash
      run: |
        aws s3 cp ./signatures s3://${{ inputs.aws_bucket_name }}/winkerberos/${{ inputs.version }}/signatures --recursive
    - name: Create a draft release with release files
      shell: bash
      if: inputs.dry_run == 'false'
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }} --notes ""
        gh release upload ${{ github.ref_name }} signatures/*.sig
    # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi
    - name: Publish distribution 📦 to PyPI
      if: inputs.dry_run == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
